{% set name = "upf_to_json" %}
{% set version = "0.9.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 57614c4c8677f04f161679ce4eddb2f55b87984605b8a5253d3d288235f56e4a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six

test:
  imports:
    - upf_to_json

about:
  home: https://github.com/simonpintarelli/upf_to_json
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Unified Pseudopotential Format to JSON converter for Python

  description: |
    UPF is a file format to describe atomic pseudo-potentials used by (DFT) density
    functional theory codes. This package provides scripts for converting UPF v1 and
    UPF v2 (Unified Pseudopotential Format) to json format as required by the SIRIUS
    DFT library SIRIUS <https://github.com/electronic-structure/SIRIUS>.

  dev_url: https://github.com/simonpintarelli/upf_to_json

extra:
  recipe-maintainers:
    - simonpintarelli
