{% set name = "upf_to_json" %}
{% set version = "0.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f6bae43e99cd747a71119e80cf4105143b85a8ee352b312a546f93d07f237122

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six

test:
  imports:
    - upf_to_json

about:
  home: https://github.com/simonpintarelli/upf_to_json
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Unified Pseudopotential Format to JSON converter for Python

  description: |
    UPF is a file format to describe atomic pseudo-potentials used by (DFT) density
    functional theory codes. This package provides scripts for converting UPF v1 and
    UPF v2 (Unified Pseudopotential Format) to json format as required by the SIRIUS
    DFT library SIRIUS <https://github.com/electronic-structure/SIRIUS>.

  dev_url: https://github.com/simonpintarelli/upf_to_json

extra:
  recipe-maintainers:
    - simonpintarelli
