{% set name = "upf_to_json" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aa5e019377e0c228dc5f95699fad2fda5cb035def1d3a18a3d2381a3328a8a11

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5

test:
  imports:
    - upf_to_json
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/simonpintarelli/upf_to_json
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Unified Pseudopotential Format to JSON converter for Python

  description: |
    UPF is a file format to describe atomic pseudo-potentials used by (DFT) density
    functional theory codes. This package provides scripts for converting UPF v1 and
    UPF v2 (Unified Pseudopotential Format) to json format as required by the SIRIUS
    DFT library SIRIUS <https://github.com/electronic-structure/SIRIUS>.

  dev_url: https://github.com/simonpintarelli/upf_to_json

extra:
  recipe-maintainers:
    - simonpintarelli
